changesetBaseRefs:
  - main
  - starknet/main

changesetIgnorePatterns:
  - .yarn/**/*

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableProgressBars: false

nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN:-}"

npmPublishRegistry: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
